import type { Metadata } from "next";
import "./globals.css";
import { Vazirmatn } from "next/font/google";
import Footer from "@/components/Footer";

const vazir = Vazirmatn({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${vazir.className} antialiased`}>{children}<Footer/></body>
    </html>
  );
}
